### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by h9052300** [Justintime50/proxlist#4]
Exception: No working proxies were found at this time, please try again later.

**Comment by Justintime50** [comment]
Hey @h9052300, this is a known exception and not an issue with the code. You will either want to adjust the criteria you are using (switching or removing the `country`, not using `google_verified`), or you can attempt to try again. The list of proxies used in this tool are constantly cycling and may not always be available. You will want to play with the input and timings and give it another try.
